CREATE OR REPLACE PACKAGE ZAM_MEN IS
PROCEDURE STWORZ_ZAMOWIENIE
(
    P_ID_KLIENTA IN P_KLIENCI.ID_KLI%TYPE
);

PROCEDURE ZAMOW
(
    P_ID_ZAM IN P_ZAMOWIENIA.ID_ZAM%TYPE,
    P_ID_TOW IN P_TOWARY.ID_TOW%TYPE,
    P_ILOSC IN P_TOWARY_ZAMOWIENIA.ILOSC%TYPE
);

PROCEDURE ZREALIZUJ
(
    P_ID_ZAM IN P_ZAMOWIENIA.ID_ZAM%TYPE,
    P_DATA IN P_ZAMOWIENIA.DATA_REALIZACJI%TYPE
);

PROCEDURE ZMIEN_ILOSC
(
    P_ID_ZAM IN P_ZAMOWIENIA.ID_ZAM%TYPE,
    P_ID_TOW IN P_TOWARY.ID_TOW%TYPE,
    P_ILOSC IN P_TOWARY_ZAMOWIENIA.ILOSC%TYPE
);
END ZAM_MEN;
/
CREATE OR REPLACE PACKAGE BODY ZAM_MEN IS
PROCEDURE STWORZ_ZAMOWIENIE
(
    P_ID_KLIENTA IN P_KLIENCI.ID_KLI%TYPE
)
IS
NEW_ZAM_ID P_ZAMOWIENIA.ID_ZAM%TYPE;
BEGIN
NEW_ZAM_ID := ZAM_SEQ.NEXTVAL;
INSERT INTO P_ZAMOWIENIA VALUES(NEW_ZAM_ID, P_ID_KLIENTA, SYSDATE, NULL);
EXCEPTION     
    WHEN OTHERS THEN         
        DBMS_OUTPUT.PUT_LINE('ZLE ID KLIENTA!'); 
END STWORZ_ZAMOWIENIE;

PROCEDURE ZAMOW 
(
    P_ID_ZAM IN P_ZAMOWIENIA.ID_ZAM%TYPE,
    P_ID_TOW IN P_TOWARY.ID_TOW%TYPE,
    P_ILOSC IN P_TOWARY_ZAMOWIENIA.ILOSC%TYPE
)
IS
ZAM_EXISTS NUMBER(1) := 0;
BEGIN
FOR REKORD IN (SELECT ID_ZAM, DATA_REALIZACJI FROM P_ZAMOWIENIA)
LOOP
    IF (REKORD.ID_ZAM LIKE P_ID_ZAM) THEN
        IF( REKORD.DATA_REALIZACJI IS NOT NULL) THEN
            ZAM_EXISTS := 2;
        ELSE
            ZAM_EXISTS := 1;
        END IF;
    END IF;
END LOOP;
IF ZAM_EXISTS = 2 THEN
    DBMS_OUTPUT.PUT_LINE('NIE MOZNA EDYTOWAC ZREALIZOWANEGO ZAMOWIENIA!');
ELSIF ZAM_EXISTS = 1 
THEN
    INSERT INTO P_TOWARY_ZAMOWIENIA 
        VALUES(101, P_ID_ZAM, P_ID_TOW, P_ILOSC);
    DBMS_OUTPUT.PUT_LINE('EDYTOWANO ISTNIEJACE ZAMOWIENIE!');
ELSE
    DBMS_OUTPUT.PUT_LINE('ZAMOWIENIE O ID: ' || P_ID_ZAM || ' NIE ISTNIEJE!');
END IF;
EXCEPTION     
    WHEN OTHERS THEN         
        DBMS_OUTPUT.PUT_LINE('ZLE ID TOWARU LUB ZAMOWIENIA!'); 
END ZAMOW;

PROCEDURE ZREALIZUJ
(
    P_ID_ZAM IN P_ZAMOWIENIA.ID_ZAM%TYPE,
    P_DATA IN P_ZAMOWIENIA.DATA_REALIZACJI%TYPE
)
IS
P_DATA_PRZYJECIA DATE;
P_IS_REALIZED DATE;
BEGIN
SELECT DATA_REALIZACJI INTO P_IS_REALIZED 
    FROM P_ZAMOWIENIA 
    WHERE ID_ZAM LIKE P_ID_ZAM;
    
IF P_IS_REALIZED IS NULL THEN
    SELECT DATA_PRZYJECIA INTO P_DATA_PRZYJECIA
        FROM P_ZAMOWIENIA 
        WHERE ID_ZAM LIKE P_ID_ZAM;
    IF(P_DATA_PRZYJECIA - P_DATA) >= 0 THEN
        DBMS_OUTPUT.PUT_LINE('ZAMOWIENIE NIE MOZE BYC SPELNIONE ZANIM ZOSTALO ZLOZONE!');
    ELSE
        UPDATE P_ZAMOWIENIA 
            SET DATA_REALIZACJI = P_DATA
            WHERE ID_ZAM LIKE P_ID_ZAM;
    DBMS_OUTPUT.PUT_LINE('ZAMOWIENIE NR: ' || P_ID_ZAM  ||
                            ' ZOSTALO ZREALIZOWANE');    
    END IF;
ELSE
    DBMS_OUTPUT.PUT_LINE('ZAMOWIENIE NR: ' || P_ID_ZAM  ||
                            ' ZOSTALO JUZ ZREALIZOWANE');
END IF;
EXCEPTION     
    WHEN OTHERS THEN         
        DBMS_OUTPUT.PUT_LINE('ZLE ID TOWARU LUB ZAMOWIENIA!'); 
END ZREALIZUJ;


PROCEDURE ZMIEN_ILOSC
(
    P_ID_ZAM IN P_ZAMOWIENIA.ID_ZAM%TYPE,
    P_ID_TOW IN P_TOWARY.ID_TOW%TYPE,
    P_ILOSC IN P_TOWARY_ZAMOWIENIA.ILOSC%TYPE
)
IS
P_DATA_REALIZACJI DATE;
BEGIN
SELECT DATA_REALIZACJI INTO P_DATA_REALIZACJI
    FROM P_ZAMOWIENIA
    WHERE ID_ZAM LIKE P_ID_ZAM;
    
IF P_DATA_REALIZACJI IS NULL THEN
    UPDATE P_TOWARY_ZAMOWIENIA
        SET ILOSC = P_ILOSC
        WHERE ID_ZAMOWIENIA LIKE P_ID_ZAM
        AND ID_TOWARU LIKE P_ID_TOW;
ELSE
    DBMS_OUTPUT.PUT_LINE('NIE MOZNA ZMIENIC ILOSCI TOWARU W ZREALIZOWANYM ZOWIENIU!');
END IF;
EXCEPTION     
    WHEN OTHERS THEN         
        DBMS_OUTPUT.PUT_LINE('ZLE ID TOWARU LUB ZAMOWIENIA!'); 
END ZMIEN_ILOSC;
END ZAM_MEN;