DROP TABLE P_TOWARY_ZAMOWIENIA;
DROP TABLE P_ZAMOWIENIA;
DROP TABLE P_TOWARY;
DROP TABLE P_KLIENCI;
DROP TABLE P_ADRESY;
DROP TABLE P_MIASTA;
DROP TABLE P_KATEGORIE;
DROP TABLE P_KOLEKCJE;
DROP TABLE P_SPECYFIKACJA;
DROP TABLE P_ROZMIARY;

CREATE TABLE P_ROZMIARY(
    ID_ROZ 	NUMBER(8) PRIMARY KEY,
    NAZWA_ROZM 	VARCHAR2 (40 BYTE) NOT NULL,
    ROZMIAR 	VARCHAR2 (40 BYTE) NOT NULL
);

CREATE TABLE P_SPECYFIKACJA(
    ID_SPEC 	NUMBER(8) PRIMARY KEY,
    KOLOR 	VARCHAR2 (40 BYTE) NOT NULL,
    ID_ROZM 	NUMBER(8),
    FOREIGN KEY (ID_ROZM) REFERENCES P_ROZMIARY (ID_ROZ)
    ON DELETE SET NULL
);

CREATE TABLE P_KOLEKCJE(
    ID_KOL 	NUMBER(8) PRIMARY KEY,
    NAZWA_KOL 	VARCHAR2 (40 BYTE) NOT NULL
);

CREATE TABLE P_KATEGORIE(
    ID_KAT 		NUMBER(8) PRIMARY KEY,
    NAZWA_KAT 		VARCHAR2 (40 BYTE) NOT NULL,
    NAZWA_POD_KAT 	VARCHAR2 (40 BYTE)
);

CREATE TABLE P_MIASTA(
    ID_MIAS 	NUMBER(8) PRIMARY KEY,
    MIASTO 	VARCHAR2 (40 BYTE) NOT NULL,
    KRAJ 	VARCHAR2 (40 BYTE) NOT NULL
);

CREATE TABLE P_ADRESY(
    ID_ADR 		NUMBER(8) PRIMARY KEY,
    ULICA 		VARCHAR2 (40 BYTE) NOT NULL,
    NR_LOKALU 		NUMBER(8),
    KOD_POCZTOWY 	VARCHAR2 (40 BYTE) NOT NULL,
    ID_MIASTA 		NUMBER(8) NOT NULL,
    FOREIGN KEY (ID_MIASTA) REFERENCES P_MIASTA (ID_MIAS)
    ON DELETE CASCADE
);

CREATE TABLE P_KLIENCI(
    ID_KLI 	NUMBER(8) PRIMARY KEY,
    IMIE 	VARCHAR2 (40 BYTE) NOT NULL,
    NAZWISKO 	VARCHAR2 (40 BYTE) NOT NULL,
    EMAIL 	VARCHAR2 (40 BYTE) NOT NULL,
    ID_ADRESU 	NUMBER(8) NOT NULL,
    FOREIGN KEY (ID_ADRESU) REFERENCES P_ADRESY (ID_ADR)
    ON DELETE CASCADE
);

CREATE TABLE P_TOWARY(
    ID_TOW 	NUMBER(8) PRIMARY KEY,
    ID_KATEG 	NUMBER(8) NOT NULL,
    ID_KOLEK 	NUMBER(8),
    NAZWA 	VARCHAR2(40 BYTE) NOT NULL,
    ID_SPECYF 	NUMBER(8) NOT NULL,
    CENA 	NUMBER(10,2) NOT NULL,
    FOREIGN KEY (ID_KATEG) REFERENCES P_KATEGORIE (ID_KAT)
    ON DELETE CASCADE,
    FOREIGN KEY (ID_KOLEK) REFERENCES P_KOLEKCJE (ID_KOL)
    ON DELETE CASCADE,
    FOREIGN KEY (ID_SPECYF) REFERENCES P_SPECYFIKACJA (ID_SPEC)
    ON DELETE CASCADE
);

CREATE TABLE P_ZAMOWIENIA(
    ID_ZAM 		NUMBER(8) PRIMARY KEY,
    ID_KLIENTA 		NUMBER(8) NOT NULL,
    DATA_PRZYJECIA 	DATE NOT NULL,
    DATA_REALIZACJI 	DATE,
    FOREIGN KEY (ID_KLIENTA) REFERENCES P_KLIENCI (ID_KLI)
    ON DELETE CASCADE
);

CREATE TABLE P_TOWARY_ZAMOWIENIA(
    ID_TZ		NUMBER(8) PRIMARY KEY,
    ID_ZAMOWIENIA	NUMBER(8) NOT NULL,
    ID_TOWARU		NUMBER(8) NOT NULL,
    ILOSC		NUMBER(8) NOT NULL,
    FOREIGN KEY (ID_TOWARU) REFERENCES P_TOWARY (ID_TOW)
    ON DELETE CASCADE,
    FOREIGN KEY (ID_ZAMOWIENIA) REFERENCES P_ZAMOWIENIA (ID_ZAM)
    ON DELETE CASCADE
);