DECLARE
ID_BESTSELLER P_TOWARY.ID_TOW%TYPE := 0;
NAZWA P_TOWARY.NAZWA%TYPE;
CENA P_TOWARY.CENA%TYPE;
KOLOR P_SPECYFIKACJA.KOLOR%TYPE;
NAZWA_ROZMIARU P_ROZMIARY.NAZWA_ROZM%TYPE;
ROZMIAR P_ROZMIARY.ROZMIAR%TYPE;
BEGIN
ID_BESTSELLER := GET_STATISTICS.BEST_SELLING_PRODUCT;
SELECT T.NAZWA, T.CENA, S.KOLOR, R.NAZWA_ROZM, R.ROZMIAR
INTO NAZWA, CENA, KOLOR, NAZWA_ROZMIARU, ROZMIAR
FROM P_TOWARY T 
LEFT OUTER JOIN P_SPECYFIKACJA S ON T.ID_SPECYF = S.ID_SPEC
LEFT OUTER JOIN P_ROZMIARY R ON S.ID_ROZM = R.ID_ROZ
WHERE T.ID_TOW LIKE ID_BESTSELLER;
DBMS_OUTPUT.PUT_LINE('DANE NAJLEPIEJ SPRZEDAJACEGO SIE TOWARU: ');
DBMS_OUTPUT.PUT_LINE('NAZWA: ' || NAZWA);
DBMS_OUTPUT.PUT_LINE('CENA: ' || CENA);
DBMS_OUTPUT.PUT_LINE('KOLOR: ' || KOLOR);
DBMS_OUTPUT.PUT_LINE('NAZWA ROZMIARU: ' || NAZWA_ROZMIARU);
DBMS_OUTPUT.PUT_LINE('ROZMIAR: ' || ROZMIAR);
END;
/
DECLARE
PRZYCHOD P_TOWARY.CENA%TYPE;
BEGIN
PRZYCHOD := GET_STATISTICS.PROFIT;
END;
/
DECLARE
ID_NAJLEPSZEGO P_KLIENCI.ID_KLI%TYPE;
IMIE P_KLIENCI.IMIE%TYPE;
NAZWISKO P_KLIENCI.NAZWISKO%TYPE;
MAIL P_KLIENCI.EMAIL%TYPE;
MIASTO P_MIASTA.MIASTO%TYPE;
KRAJ P_MIASTA.KRAJ%TYPE;
BEGIN
ID_NAJLEPSZEGO := GET_STATISTICS.BEST_CLIENT;
SELECT K.IMIE, K.NAZWISKO, K.EMAIL, M.MIASTO, M.KRAJ
INTO IMIE, NAZWISKO, MAIL, MIASTO, KRAJ
FROM P_KLIENCI K
INNER JOIN P_ADRESY A ON K.ID_ADRESU = A.ID_ADR
INNER JOIN P_MIASTA M ON A.ID_MIASTA = M.ID_MIAS
WHERE K.ID_KLI LIKE ID_NAJLEPSZEGO;
DBMS_OUTPUT.PUT_LINE('DANE NAJWIERNIEJSZEGO KLIENTA: ');
DBMS_OUTPUT.PUT_LINE('IMIE: ' || IMIE);
DBMS_OUTPUT.PUT_LINE('NAZWISKO: ' || NAZWISKO);
DBMS_OUTPUT.PUT_LINE('EMAIL: ' || MAIL);
DBMS_OUTPUT.PUT_LINE('MIASTO: ' || MIASTO);
DBMS_OUTPUT.PUT_LINE('KRAJ: ' || KRAJ);
END;
/
DECLARE
ID_KLI P_KLIENCI.ID_KLI%TYPE := 113;
BEGIN
ZAM_MEN.STWORZ_ZAMOWIENIE(ID_KLI);
END;
/
DECLARE
ID_ZAM P_ZAMOWIENIA.ID_ZAM%TYPE := 110;
ID_TOW P_TOWARY.ID_TOW%TYPE := 140;
ILOSC P_TOWARY_ZAMOWIENIA.ILOSC%TYPE := 3;
BEGIN
ZAM_MEN.ZAMOW(ID_ZAM, ID_TOW, ILOSC);
END;
/
DECLARE
ID_ZAM P_ZAMOWIENIA.ID_ZAM%TYPE := 112;
ID_TOW P_TOWARY.ID_TOW%TYPE := 140;
ILOSC P_TOWARY_ZAMOWIENIA.ILOSC%TYPE := 3;
BEGIN
ZAM_MEN.ZAMOW(ID_ZAM, ID_TOW, ILOSC);
END;
/
DECLARE
ID_ZAM P_ZAMOWIENIA.ID_ZAM%TYPE := 111;
ID_TOW P_TOWARY.ID_TOW%TYPE := 140;
ILOSC P_TOWARY_ZAMOWIENIA.ILOSC%TYPE := 3;
BEGIN
ZAM_MEN.ZAMOW(ID_ZAM, ID_TOW, ILOSC);
END;
/
DECLARE
ID_ZAM P_ZAMOWIENIA.ID_ZAM%TYPE := 110;
ID_TOW P_TOWARY.ID_TOW%TYPE := 140;
ILOSC P_TOWARY_ZAMOWIENIA.ILOSC%TYPE := 3;
BEGIN
ZAM_MEN.ZMIEN_ILOSC(ID_ZAM, ID_TOW, ILOSC);
END;
/
DECLARE
ID_ZAM P_ZAMOWIENIA.ID_ZAM%TYPE := 111;
ID_TOW P_TOWARY.ID_TOW%TYPE := 140;
ILOSC P_TOWARY_ZAMOWIENIA.ILOSC%TYPE := -1;
BEGIN
ZAM_MEN.ZMIEN_ILOSC(ID_ZAM, ID_TOW, ILOSC);
END;
/
DECLARE
ID_ZAM P_ZAMOWIENIA.ID_ZAM%TYPE := 111;
ID_TOW P_TOWARY.ID_TOW%TYPE := 140;
ILOSC P_TOWARY_ZAMOWIENIA.ILOSC%TYPE := 1;
BEGIN
ZAM_MEN.ZMIEN_ILOSC(ID_ZAM, ID_TOW, ILOSC);
END;
/
DECLARE
ID_ZAM P_ZAMOWIENIA.ID_ZAM%TYPE := 111;
DATA P_ZAMOWIENIA.DATA_REALIZACJI%TYPE := '19/06/03';
BEGIN
ZAM_MEN.ZREALIZUJ(ID_ZAM, DATA);
END;
/
DECLARE
ID_ZAM P_ZAMOWIENIA.ID_ZAM%TYPE := 110;
DATA P_ZAMOWIENIA.DATA_REALIZACJI%TYPE := '20/06/03';
BEGIN
ZAM_MEN.ZREALIZUJ(ID_ZAM, DATA);
END;
/
DECLARE
ID_ZAM P_ZAMOWIENIA.ID_ZAM%TYPE := 111;
DATA P_ZAMOWIENIA.DATA_REALIZACJI%TYPE := '20/06/03';
BEGIN
ZAM_MEN.ZREALIZUJ(ID_ZAM, DATA);
END;




