SELECT COUNT(ID_KOLEK) FROM P_TOWARY;

SELECT T.NAZWA, KA.NAZWA_KAT, KA.NAZWA_POD_KAT, KO.NAZWA_KOL, T.CENA
FROM P_TOWARY T 
INNER JOIN P_KATEGORIE KA ON (T.ID_KATEG = KA.ID_KAT)
LEFT OUTER JOIN P_KOLEKCJE KO ON (T.ID_KOLEK = KO.ID_KOL)
GROUP BY NAZWA, CENA, KA.NAZWA_KAT, KO.NAZWA_KOL, KA.NAZWA_POD_KAT
ORDER BY T.CENA ASC;

SELECT T.NAZWA, TZ.ILOSC, TZ.ID_ZAMOWIENIA
FROM P_TOWARY T
INNER JOIN P_TOWARY_ZAMOWIENIA TZ 
ON (T.ID_TOW = TZ.ID_TOWARU)
ORDER BY ILOSC DESC;

SELECT Z.ID_ZAM 
FROM P_ZAMOWIENIA Z
INNER JOIN P_KLIENCI K ON K.ID_KLI = Z.ID_KLIENTA
INNER JOIN P_ADRESY A ON K.ID_ADRESU = A.ID_ADR
WHERE A.ID_ADR IN (101, 102, 103);

SELECT T.NAZWA, T.CENA FROM P_TOWARY T
INNER JOIN P_SPECYFIKACJA S ON T.ID_SPECYF = S.ID_SPEC
INNER JOIN P_ROZMIARY R ON S.ID_ROZM = R.ID_ROZ
WHERE R.NAZWA_ROZM LIKE 'M_L';
